### ISSUE TITLE
internal problems...

### ISSUE THREAD

**Issue by tripodsan** [mtdowner/helix-boilerplate#3]
hi @mtdowner ,

I just saw in our logs that there are some unexpected errors with your page.... it looks like you can't preview the index page.
I'll look at it asap... sorry for the hickup.

**Comment by mtdowner** [comment]
Hi :) wow, thanks! I'm super new to web development and the terminology. I was thinking how I still managed to mess something up despite the walkthrough being so perfectly written and easy to follow along! I appreciate you looking into it, but there is still a possibility I added the wrong folder link 😅. I'll be on the lookout for any updates, thank you again!!

**Comment by tripodsan** [comment]
I don't think you did anything wrong. I just got lucky to trigger the one edge case that causes an error converting the google document ;-)  I'll keep you posted when the problem is fixed.

**Comment by tripodsan** [comment]
@mtdowner the problem is fixed. there was a bug in the google docs to markdown processor that was preventing you from previewing the `index` document. The bug was caused by a _code block_ marker that mysteriously wasn't closed :-) 

In any case, your homepage is now previewed.

**Comment by mtdowner** [comment]
@tripodsan You are awesome! Thank you for looking into this, I've been wanting to get this going for a minute now. Can't wait to get this running, thanks again!! 😄😊
